### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by PW999**
Pull request with changes to allow grouping URL's with pathvariables and additional documentation to help configuring newrelic-timing, as per #8

### CODE REVIEW

**Comment by pitr** [comment]
tests are failing because of indentation issue, plz fix. Otherwise :+1: +1, thanks @PW999

/cc @dterror

**Comment by dterror** [comment]
looks good
+1 pending indentation

**Comment by PW999** [comment]
That is odd, tests ran fine on my computer. Replaced a tab with spaces, hope travis build works fine now.

**Comment by PW999** [comment]
Second build is now failing due to a missing dependency issue:
```
npm ERR! Error: No compatible version found: minimatch@'^2.0.1'
``` 

Can this pull request be merged or is there something else I have to change or alter ?

**Comment by pitr** [comment]
I'd say it's safe to merge. Seems like a problem with one of travis workers /cc @dterror

**Comment by rpocklin** [comment]
What's the status of this?

**Comment by pitr** [comment]
looks good, thanks @rpocklin for a bump

**Pull request merged**
